nome = str(input('Digite aqui o seu nome:'))
M = nome.upper()
print(M)
min = nome.lower()
print(min)
semespaço = nome.replace(' ','')
total = len(semespaço)
print('O total de letras e {}'.format(total))
strip = nome.split()
print('o primeiro nome tem {}'.format(len(strip)))